version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    image: hk2014/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    image: hk2014/frontend:latest
    ports:
      - "8081:8081"
    depends_on:
      - backend